"$schema"= 'https://starship.rs/config-schema.json'
# comment for sheme
add_newline = true

format="\\[$os\\]\\[$username$hostname\\]\\[$localip\\] \\[$directory\\] [➜](bold bright-green) "

[username]
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@ [$hostname](bold #e20074)'
disabled = false

[directory]
format='[$path]($style)[$read_only]($read_only_style)'

[os]
format = '[$symbol]($style)'
style = 'bold cyan'
disabled = false

[os.symbols]
Windows = ""
Debian = ""
Macos = ""
Ubuntu = ""

[localip]
ssh_only = false
format = '[$localipv4]($style)'
style = 'bold white'
disabled = false
